### ISSUE TITLE
missing variable

### ISSUE THREAD

**Issue by msilkjr** [MagnusBoxMike/Syncro-Rmm#6]
the code is missing " $mbu = $mbu " it talks about it in the readme however it is missing in the code. It must be added.

**Comment by RaneLafraze** [comment]
Hi @msilkjr 
Thank you for creating this Issue and bringing it to our attention. Which specific script was the `%mbu` variable missing from?

**Comment by msilkjr** [comment]
sorry its the " Delete User "

**Comment by RaneLafraze** [comment]
Thank you for catching that! I just issued a commit (f9d4e04a04def843d8f6f27d16c33752e412a561) and added that variable to the script
